language: python

python:
    - "2.7"
    - "pypy"

services:
    # for example 
    # - redis-server

#install deps
install:
    - "pip install . -q"
    - "pip install -r requirements.txt -q"
    #- "python setup.py install"

# tests
script: 
    - "nosetests tests"
